version: "2.3"
services:
  flask:
    build: ./flaskapp
    container_name: flask
    ports:
      - "5000:5000"
      - "8085:8085"
    restart: always
    environment:
      - APP_NAME=app
    expose:
      - 5000
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - flask
    depends_on:
      - flask